DELETE http://localhost:8080/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjM2MDc2NTksInVzZXJJZCI6Mn0.R5mD6h32vOklUotpa7u4Y_NX_V2Kh4YcV3uVB7wF9sg
